name: Trigger auto deployment for containerappmcpv2

on:
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/containerappmcpv2-AutoDeployTrigger-b34df7db-b070-4672-87ae-1388aaed5abd.yml'
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONTAINERAPPMCPV2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPMCPV2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPMCPV2_AZURE_SUBSCRIPTION_ID }}
          auth-type: IDENTITY

      - name: Log in to Container Registry
        run: |
          az acr login --name containerregistrymcpv2

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: containerregistrymcpv2.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPMCPV2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPMCPV2_REGISTRY_PASSWORD }}
          containerAppName: containerappmcpv2
          resourceGroup: RG_MCP
          imageToBuild: containerregistrymcpv2.azurecr.io/containerappmcpv2:${{ github.sha }}
